name: Build Applications

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git -b stable --depth 1 $HOME/flutter
          echo "$HOME/flutter/bin" >> $GITHUB_PATH
          flutter doctor

      - name: Build Android APK
        run: |
          flutter build apk

      - name: Build iOS App
        run: |
          flutter build ios --release --no-codesign

      - name: Build macOS App
        run: |
          flutter build macos --release

      - name: Archive Applications
        run: |
          zip -r build_outputs_${{ steps.version.outputs.date }}.zip build/app/outputs/flutter-apk/app-release.apk build/ios/iphoneos build/macos/Build/Products/Release
        env:
          version_tag: ${{ steps.version.outputs.date }}

      - name: Get the date
        id: version
        run: echo "::set-output name=date::$(date +'%y.%m.%d')"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-builds-${{ steps.version.outputs.date }}
          path: build_outputs_${{ steps.version.outputs.date }}.zip