name: SS2kConfigApp
description: Configures the SmartSpin2k using BLE

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/ss2k_wiki_banner.png
    - assets/ss2kv3.png
