name: SS2kConfigApp
description: Configures the SmartSpin2k using BLE
version: 1.0.3+1

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <=4.0.0"
  # change this in ci_post_clone.sh as well
  flutter: ">3.19.0 <=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.32.8
  #dynamic_color: ^1.6.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  shared_preferences: ^2.2.0
  file_picker: ^7.0.0
  #flutter_ota: ^0.1.4
  wakelock_plus: ^1.2.5
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  json_theme: ^6.4.1+5
  fl_chart: ^0.68.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/appainter_theme.json