name: SS2kConfigApp
description: Configures the SmartSpin2k using BLE

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.2.4 <3.16.8"

dependencies:
  
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.31.8
  #dynamic_color: ^1.6.9
  flutter_launcher_icons: ^0.13.1
  material_color_utilities: ^0.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/ss2k_wiki_banner.png
    - assets/ss2kv3.png
